name: Feature Request
description: No im am not adding the mod folder, because i want these mods to be open sourced
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the base engine?
    validations:
      required: true
